[package]
name = "inference"
license.workspace = true
version.workspace = true
edition.workspace = true
publish = false

[features]
cuda = ["burn/cuda-jit"]
ndarray = ["burn/ndarray"]
wgpu = ["burn/wgpu"]

openblas = ["burn/openblas"]
openblas-system = ["burn/openblas-system"]
fusion = ["burn/fusion"]

[dependencies]
birefnet-burn = { path = "../../birefnet" }
burn = { workspace = true, default-features = false }

anyhow = "1"
clap = { version = "^4.5.20", features = ["derive"] }
image = { version = "^0.25.2", default-features = false, features = ["png", "jpeg"] }
num-traits = "^0.2.19"
