[package]
name = "birefnet-loss"
description = "Comprehensive loss functions for deep learning segmentation tasks in Burn"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
burn = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["flex", "autodiff"] }

[lints]
workspace = true
