[package]
name = "birefnet-metric"
description = "Custom evaluation metrics for BiRefNet implemented in Rust using Burn framework"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true
keywords = ["birefnet", "metrics", "evaluation", "segmentation", "burn"]
categories = ["computer-vision"]

[dependencies]
burn = { workspace = true, features = ["train"] }
birefnet-util = { path = "../birefnet-util" }

[dev-dependencies]
burn = { workspace = true, features = ["flex", "train"] }

[lints]
workspace = true
