[package]
name = "birefnet-extra-ops"
description = "Additional operations for the Burn deep learning framework"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
burn = { workspace = true }
libm = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["flex", "autodiff"] }
rstest = { workspace = true }

[lints]
workspace = true
