[package]
name = "birefnet-burn"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
burn = { workspace = true, default-features = false, features = ["std"] }
libm = { workspace = true }
